// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e144b4e1-58d5-4313-9f77-914c43b59c8a";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRghbledColorChange();
void onLightSensorValChange();

CloudColor rghbledColor;
int lightSensorVal;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(rghbledColor, READWRITE, ON_CHANGE, onRghbledColorChange);
  ArduinoCloud.addProperty(lightSensorVal, READWRITE, 1 * SECONDS, onLightSensorValChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
